List<String> quizNames = [
  'Brasil',
  'Vasco',
  'Flamengo',
  'Fluminense',
  'Botafogo',
  'Corinthians',
  'Sao Paulo',
  'Palmeiras',
  'Santos',
  'Bragantino',
  'Atletico MG',
  'Cruzeiro',
  'Gremio',
  'Internacional',
  'Bahia',
  'Fortaleza',
  'Vitória',
  'Real Madrid',
  'Barcelona',
  'Jogadores',
];
